### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by batininhani** [sd-soleaio/deobfuscator-io#7]
deobfuscator.js:117
        } catch {}
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deobfuscator-io@1.0.0 start: `node src/deobfuscator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deobfuscator-io@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by sd-soleaio** [comment]
Hi, can you send a sample script that this error occurs on.

**Comment by batininhani** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\batin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.14.9
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle deobfuscator-io@1.0.0~prestart: deobfuscator-io@1.0.0
6 info lifecycle deobfuscator-io@1.0.0~start: deobfuscator-io@1.0.0
7 verbose lifecycle deobfuscator-io@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle deobfuscator-io@1.0.0~start: PATH: C:\Users\batin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\batin\Downloads\deobfuscator-io-master\deobfuscator-io-master\node_modules\.bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files\AdoptOpenJDK\jdk-12.0.2.10-hotspot\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\MinGW\bin;C:\Program Files\nodejs\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\batin\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\batin\AppData\Local\Programs\Python\Python38\;C:\Users\batin\.windows-build-tools\python27\;C:\Users\batin\.cargo\bin;C:\Users\batin\AppData\Local\Microsoft\WindowsApps;C:\Users\batin\.dotnet\tools;C:\Python27;C:\Python27\Scripts;C:\Users\batin\AppData\Roaming\npm;C:\Users\batin\AppData\Local\Programs\Python\Python38-32\;C:\xampp\php\;C:\Users\batin\AppData\Local\ComposerSetup\bin;C:\Users\batin\AppData\Roaming\Composer\vendor\bin;C:\Users\batin\.dotnet\tools
9 verbose lifecycle deobfuscator-io@1.0.0~start: CWD: C:\Users\batin\Downloads\deobfuscator-io-master\deobfuscator-io-master
10 silly lifecycle deobfuscator-io@1.0.0~start: Args: [ '/d /s /c', 'node src/deobfuscator.js' ]
11 silly lifecycle deobfuscator-io@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle deobfuscator-io@1.0.0~start: Failed to exec start script
13 verbose stack Error: deobfuscator-io@1.0.0 start: `node src/deobfuscator.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\batin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\batin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid deobfuscator-io@1.0.0
15 verbose cwd C:\Users\batin\Downloads\deobfuscator-io-master\deobfuscator-io-master
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\batin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error deobfuscator-io@1.0.0 start: `node src/deobfuscator.js`
22 error Exit status 1
23 error Failed at the deobfuscator-io@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
